\section{RAII-classes}
\subsection{Пример}
Начнем с примера.

У нас есть функция \mintinline{c++}{my_fopen()} для открытия файлов на чтение, которая в случаи ошибки открытия файла кидает исключение.
\begin{minted}[linenos, frame=lines, framesep=2mm, tabsize = 4, breaklines]{c++}
FILE* my_fopen(char const* filename) {
    FILE* result = fopen(filename, "r");
    if (!result)
        throw std::runtime_error("fopen failed");

    return result;
}
\end{minted}
Пусть необходимо в функции \mintinline{c++}{process_files()} открыть несколько файлов.
\begin{minted}[linenos, frame=lines, framesep=2mm, tabsize = 4, breaklines]{c++}
void process_files() {
    FILE* f1 = fopen("foo");
    FILE* f2 = fopen("bar");
    FILE* f3 = fopen("baz");

    fclose(f3);
    fclose(f2);
    fclose(f1);
}
\end{minted}
Но такой код не гарантирует закрытие файлов в случае возникновения исключения.
Тогда давайте вставим проверку исключений:
\begin{minted}[linenos, frame=lines, framesep=2mm, tabsize = 4, breaklines]{c++}
void process_files() {
    FILE* f1 = fopen("foo");
    try {
        FILE* f2 = fopen("bar");
        try {
            FILE* f3 = fopen("baz");
            try {
                /* ... */
            }
            catch(...) {
                fclose(f3);
                throw;
            }
            fclose(f3);
        }
        catch(...) {
            fclose(f2);
            throw;
        }
        fclose(f2);
    }
    catch(...) {
        fclose(f1);
        throw;
    }
    fclose(f1);
}
\end{minted}
Итого код увеличился в несколько раз.


Однако, с помощью RAII-класса файловых дескрипторов \mintinline{c++}{Reader}, можно упростить код:
\begin{minted}[linenos, frame=lines, framesep=2mm, tabsize = 4, breaklines]{c++}
void process_files() {
    Reader f1("foo");
    Reader f2("bar");
    Reader f3("baz");
}
\end{minted}

Этот код получился довольно простой и безопасный. Почему безопасный? Потому, что объект \mintinline{c++}{Reader} открывает файл в конструкторе и закрывает в деструкторе. И если возникнет исключение, то при раскрутке стека удаляться все локальные объекты, в том числе и файловые дескрипторы, закрывая файлы. Если же какой-то файл не успел открыться, то не успел и создаться объект отвечающий за него.

Реализация \mintinline{c++}{Reader} могла бы выглядеть так:
\begin{minted}[linenos, frame=lines, framesep=2mm, tabsize = 4, breaklines]{c++}
class Reader {
public:
    Reader(char const *filename):
        _file(fopen(filename, "r")) { } //захват ресурса

    ~Reader() {
        fclose(_file); // освобождение ресурса
    }

    Reader(Reader const &) = delete;
    Reader operator=(Reader const &) = delete;

private:
    FILE *_file;
};
\end{minted}
Важно, что мы запретили копирование объектов класса, так как за один файл должен отвечать один объект. Без этого файл мог бы два раза закрыться.

Это удобная идея получила название <<RAII>>.

\subsection{Определение}

\textbf{<<Resource Acquision is Initialozation>>} или <<Захват ресурса - это инициализация>> - это идиома класса, который инкапсулирует управление каким-то ресурсом. Она значит, что объект этого класса, получает доступ к ресурсу и удерживает его в течении своей жизни, а потом этот ресурс высвобождается при уничтожении объекта.
В конструкторе он должен захватить ресурс(открыть файл, выделить файл и т. д.), а в десткрукторе освободить его(закрыть файл, освободить память и т. д.).

Также важно подумать, что должно происходить при копировании объекта, часто мы явно запрещаем это делать. Так как иначе ресурс может освободиться два раза.

\subsection{Зачем это нужно?}
\begin{itemize}
\item Удобство кода: не нужно явно каждый раз в конце тела функции освобождать ресурсы и учитывать какие ресурсы успели захватиться, а какие нет. Когда выполнение текущего блока будет завершено, локальные объекты RAII-классов удалятся и необходимы ресурсы освободятся автоматически.
\item Безопасность исключений: Если вызывается исключение, то гарантируется, что стек очиститься и все локальные объекты удаляться, а значит и освободятся ресурсы.
\item Часто важно освобождать ресурсы в обратном порядке, относительно того, как они были захвачены. Это как раз поддерживается раскруткой стека при удалении локальных объектов.
\end{itemize}

\textcolor{red}{NB}) Это идиома работает не только в С++, а любом языке с предсказуемым временем жизни объектов.

\textcolor{red}{NB}) RAII часто встречается стандартной библиотеке:
\begin{itemize}
\item Smart pointers -- инкапсулируют несколько видов управления памятью
\item i/ofstream -- инкапсулиет управление файлом
\item Различные контейнеры stl -- инкапсулируют управление памятью, для хранение объектов в структурах данных.
\end{itemize}

\subsection{Best practice}
\begin{itemize}
\item
Начиная с с++11 есть возможность хранить RAII-классы в контейнерах с помощью механизма перемещения, для этого необходимо реализовать конструктор перемещения.
\item
Вернемся к предыдущему примеру Reader.
Пусть в конструкторе есть код, который может сгенерировать исключение, тогда возникает проблема освобождения ресурса.

\begin{minted}[linenos, frame=lines, framesep=2mm, tabsize = 4, breaklines]{c++}
Reader::Reader(char const *filename, char const *mode)
    : _file(fopen(filename, mode)) {
    //код допускающий исключение
}
\end{minted}
Если в теле конструктора происходит исключение, то деструктор не вызовется, так как объект не считается созданным. Что делать?

Решение № 1
Написать try-catch:
\begin{minted}[linenos, frame=lines, framesep=2mm, tabsize = 4, breaklines]{c++}
class Reader {
public:
    Reader(char const *filename, char const *mode) try
        : _file(fopen(filename, mode)) {
    //код допускающий исключение
    }
    catch (...) {
        destruct_obj();
    }

    ~Reader() {
        destruct_obj();
    }

private:
    void destruct_obj() {
        fclose(_file);
    }
    FILE * _file;
};
\end{minted}
Но это вызывает сильное раздувание кода.

Решение № 2
Можно сделать отдельный подкласс, который хранит в себе ресурс.
\begin{minted}[linenos, frame=lines, framesep=2mm, tabsize = 4, breaklines]{c++}
class Reader {
    struct ReaderHandle {
        ReaderHandle(FILE *fh)
        : _fh(fh) { }

        ~ReaderHandle() {
            fclose(_fh);
        }

        FILE *_fh;
    };
public:
    Reader(char const * filename, char const * mode)
    : _file(fopen(filename, mode)) {
        // код допускающий исключения
    }

    ~Reader() = default;

private:
    ReaderHandle _file;
};
\end{minted}
Теперь все тоже хорошо, так как при возникновении исключения, вызовутся деструкторы от все членов класса.

Решение № 3 (начиная с С++11)
Делегирующий конструктор.
\begin{minted}[linenos, frame=lines, framesep=2mm, tabsize = 4, breaklines]{c++}
class Reader
{
    Reader(FILE * file)
        : _file(file) { }

public:
    Reader(char const * filename, char const * mode)
        : Reader(fopen(filename, mode)) {
        // код допускающий исключения
    }

    ~Reader() {
        fclose(_file);
    }

private:
    FILE *_file;
};
\end{minted}
Если возникнет исключение, то объект к этому времени будет считаться созданным, так как один конструктор уже отработал. Благодаря этому он уничтожится автоматически.
\end{itemize}
